import { api } from "./api";
import { Automation } from "@/types/automation";

export interface PlanRequest {
  description: string;
  site_url?: string;
  auth_hint?: string;
}

export interface PlannerDraft {
  automation_name: string;
  version: number;
  auth?: Record<string, unknown>;
  steps: Array<Record<string, unknown>>;
  notes?: string[];
}

export async function fetchPlan(req: PlanRequest): Promise<PlannerDraft> {
  return api.post<PlannerDraft>("/planner/plan", req);
}

/** Convert a PlannerDraft into the shape the existing `createAutomation` expects. */
export function draftToAutomation(draft: PlannerDraft): Omit<Automation, "id" | "created_at" | "updated_at"> {
  return {
    name: draft.automation_name,
    description: `Generated by AI Planner`,
    erp_url: "",
    instructions: "",
    steps: draft.steps,
    auth: draft.auth,
    inputs_schema: null,
    outputs: [],
    credentials: {},
    is_active: false,
  } as Omit<Automation, "id" | "created_at" | "updated_at">;
}
