from unittest.mock import MagicMock, patch
import pytest


def test_endpoint_returns_dsl_draft():
    from app.main import app
    from fastapi.testclient import TestClient
    client = TestClient(app)

    fake_draft = {
        "automation_name": "ping",
        "version": 1,
        "steps": [{"id": "x", "goto": "https://x"}],
        "notes": [],
    }

    async def fake_plan(description, site_url, auth_hint="", model=None):
        return fake_draft

    with patch("app.api.routes.planner.plan_automation", side_effect=fake_plan):
        resp = client.post("/api/planner/plan", json={
            "description": "ping example",
            "site_url": "https://example.com",
            "auth_hint": "",
        })
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["automation_name"] == "ping"
    assert isinstance(body["steps"], list)


def test_endpoint_rejects_empty_description():
    from app.main import app
    from fastapi.testclient import TestClient
    client = TestClient(app)
    resp = client.post("/api/planner/plan", json={
        "description": "",
        "site_url": "https://x.com",
    })
    assert resp.status_code == 400


def test_endpoint_rejects_missing_description():
    from app.main import app
    from fastapi.testclient import TestClient
    client = TestClient(app)
    resp = client.post("/api/planner/plan", json={"site_url": "https://x.com"})
    assert resp.status_code == 422


def test_endpoint_propagates_openai_errors():
    from app.main import app
    from fastapi.testclient import TestClient
    client = TestClient(app)

    async def fake_plan(**kw):
        raise RuntimeError("openai is down")

    with patch("app.api.routes.planner.plan_automation", side_effect=fake_plan):
        resp = client.post("/api/planner/plan", json={
            "description": "x",
            "site_url": "https://x",
        })
    assert resp.status_code == 500


def test_draft_with_auth_step_round_trips_through_create(monkeypatch):
    """A planner output with an auth step persists intact via createAutomation.

    This is the integration check that the final-review fix relied on:
    `AutomationCreate` does NOT have an `auth` field, so the auth block MUST
    live inside `steps` (specifically as steps[0] = {"id":"auth","auth":{...}}).
    """
    import os
    if not os.environ.get("SUPABASE_URL"):
        pytest.skip("SUPABASE_URL not set in test env")

    from app.main import app
    from fastapi.testclient import TestClient
    client = TestClient(app)

    auth_payload = {
        "type": "form_login",
        "url": "https://app.apvs.vc",
        "credentials_ref": "apvs_login",
        "selectors": {"user": "input", "pass": "input", "submit": "button"},
        "success_assert": {"selector": ".dashboard", "timeout_ms": 5000},
    }
    planner_draft = {
        "automation_name": "auth_roundtrip_test",
        "version": 1,
        "steps": [
            {"id": "auth", "auth": auth_payload},
            {"id": "do_thing", "goto": "https://app.apvs.vc/x"},
        ],
        "notes": [],
    }

    async def fake_plan(**kw):
        return planner_draft

    # Patch the planner call.
    with patch("app.api.routes.planner.plan_automation", side_effect=fake_plan):
        plan_resp = client.post("/api/planner/plan", json={
            "description": "thing",
            "site_url": "https://app.apvs.vc",
        })
    assert plan_resp.status_code == 200
    plan_body = plan_resp.json()

    # Now POST the planner output to /api/automations (the create endpoint).
    create_resp = client.post("/api/automations", json={
        "name": plan_body["automation_name"],
        "description": "Generated by AI Planner",
        "erp_url": "",
        "instructions": "",
        "steps": plan_body["steps"],
        "credentials": {},
        "outputs": [],
    })
    assert create_resp.status_code in (200, 201), create_resp.text
    created = create_resp.json()

    # The auth block must be preserved INSIDE steps[0] (AutomationCreate drops
    # top-level `auth` since it has no such field; the runner reads it from
    # steps[0] instead).
    assert created["steps"][0]["id"] == "auth"
    assert created["steps"][0]["auth"]["credentials_ref"] == "apvs_login"

    # Cleanup.
    client.delete(f"/api/automations/{created['id']}")
